#pragma once

#define VI_CTRL_FIELDS(M) \
    M(TYPE,0,1) M(GAMMA_DITHER_ENABLE,2,2) M(GAMMA_ENABLE,3,3) M(DIVOT_ENABLE,4,4) \
    M(VBUS_CLOCK_ENABLE,5,5) M(SERRATE,6,6) M(TEST_MODE,7,7) M(AA_MODE,8,9) \
    M(KILL_WE,11,11) M(PIXEL_ADVANCE,12,15) M(DEDITHER_ENABLE,16,16)
#define VI_ORIGIN_FIELDS(M) M(ORIGIN, 0, 23)
#define VI_WIDTH_FIELDS(M) M(WIDTH, 0, 11)
#define VI_V_INTR_FIELDS(M) M(V_INTR,0,9)
#define VI_V_CURRENT_FIELDS(M) M(V_FIELD,0,0) M(V_CURRENT,1,9)
#define VI_BURST_FIELDS(M) M(HSYNC_WIDTH, 0, 7)  M(BURST_WIDTH, 8, 15)  M(VSYNC_HEIGHT, 16, 19)  M(BURST_START, 20, 29)
#define VI_V_TOTAL_FIELDS(M) M(V_TOTAL,0,9)
#define VI_H_TOTAL_FIELDS(M) M(H_TOTAL,0,11)  M(LEAP,16,20)
#define VI_H_TOTAL_LEAP_FIEDS(M) M(LEAP_B,0,11)  M(LEAP_A,16,27)
#define VI_H_VIDEO_FIELDS(M) M(H_END,0,9) M(H_START,16,25)
#define VI_V_VIDEO_FIELDS(M) M(V_END,0,9) M(V_START,16,25)
#define VI_V_BURST_FIELDS(M) M(V_BURST_END, 0, 9)  M(V_BURST_START, 16, 25)
#define VI_X_SCALE_FIELDS(M) M(X_SCALE, 0, 11)  M(X_OFFSET, 16, 25)
#define VI_Y_SCALE_FIELDS(M) M(Y_SCALE, 0, 11)  M(Y_OFFSET, 16, 25)
#define VI_TEST_ADDR_FIELDS(M) M(TEST_ADDR, 0, 6) 
#define VI_STAGED_DATA_FIELDS(M) M(STAGED_DATA, 0, 31)


#include "Base/Base.h"
#include "Base/Bus.h"

namespace esx {


	DEFINE_REGISTER_LAYOUT(VI_CTRL_Register, U32, VI_CTRL_FIELDS)
	DEFINE_REGISTER_LAYOUT(VI_ORIGIN_Register, U32, VI_ORIGIN_FIELDS)
	DEFINE_REGISTER_LAYOUT(VI_WIDTH__Register, U32, VI_WIDTH_FIELDS)
	DEFINE_REGISTER_LAYOUT(VI_V_INTR_Register, U32, VI_V_INTR_FIELDS)
	DEFINE_REGISTER_LAYOUT(VI_V_CURRENT_Register, U32, VI_V_CURRENT_FIELDS)
	DEFINE_REGISTER_LAYOUT(VI_BURST_Register, U32, VI_BURST_FIELDS)
	DEFINE_REGISTER_LAYOUT(VI_V_TOTAL_Register, U32, VI_V_TOTAL_FIELDS)
	DEFINE_REGISTER_LAYOUT(VI_H_TOTAL_Register, U32, VI_H_TOTAL_FIELDS)
	DEFINE_REGISTER_LAYOUT(VI_H_TOTAL_LEAP_Register, U32, VI_H_TOTAL_LEAP_FIEDS)
	DEFINE_REGISTER_LAYOUT(VI_H_VIDEO_Register, U32, VI_H_VIDEO_FIELDS)
	DEFINE_REGISTER_LAYOUT(VI_V_VIDEO_Register, U32, VI_V_VIDEO_FIELDS)
	DEFINE_REGISTER_LAYOUT(VI_V_BURST_Register, U32, VI_V_BURST_FIELDS)
	DEFINE_REGISTER_LAYOUT(VI_X_SCALE_Register, U32, VI_X_SCALE_FIELDS)
	DEFINE_REGISTER_LAYOUT(VI_Y_SCALE_Register, U32, VI_Y_SCALE_FIELDS)
	DEFINE_REGISTER_LAYOUT(VI_TEST_ADDR_Register, U32, VI_TEST_ADDR_FIELDS)
	DEFINE_REGISTER_LAYOUT(VI_STAGED_DATA_Register, U32, VI_STAGED_DATA_FIELDS)


	class RCP;

	class VideoInterface {
	public:
		VideoInterface(RCP* rcp);
		~VideoInterface();

		void init();
		void clock(U64 clocks);

		void store(U32 address, U32 value);
		U32 load(U32 address);

		void reset();

		inline static U64 VIClocksToCPUClocks(U64 VIClocks);
		inline static U64 CPUClocksToVIClocks(U64 CPUClocks);

	private:
		void scheduleVIEvents();
	private:
		StringView mName = "VideoInterface";

		RCP* mRCP;

		VI_CTRL_Register			VI_CTRL;
		VI_ORIGIN_Register			VI_ORIGIN;
		VI_WIDTH__Register			VI_WIDTH;
		VI_V_INTR_Register			VI_V_INTR;
		VI_V_CURRENT_Register		VI_V_CURRENT;
		VI_BURST_Register			VI_BURST;
		VI_V_TOTAL_Register			VI_V_TOTAL;
		VI_H_TOTAL_Register			VI_H_TOTAL;
		VI_H_TOTAL_LEAP_Register	VI_H_TOTAL_LEAP;
		VI_H_VIDEO_Register			VI_H_VIDEO;
		VI_V_VIDEO_Register			VI_V_VIDEO;
		VI_V_BURST_Register			VI_V_BURST;
		VI_X_SCALE_Register			VI_X_SCALE;
		VI_Y_SCALE_Register			VI_Y_SCALE;
		VI_TEST_ADDR_Register		VI_TEST_ADDR;
		VI_STAGED_DATA_Register		VI_STAGED_DATA;

		BIT mCountLine;
		BIT mFirstLine;
	};

}